name: Run tests

on:
  pull_request:
  push:
    branches:
      - main
      - differentiability

# needed to allow julia-actions/cache to delete old caches that it has created
permissions:
  actions: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Capytaine
      run: |
         python -m venv /home/runner/.capy-venv
         /home/runner/.capy-venv/bin/python -m pip install -r test/requirements.txt
    - name: Setup Julia
      uses: julia-actions/setup-julia@v2

    - name: Setup cache for Julia packages
      uses: julia-actions/cache@v2

    - name: Build package
      uses: julia-actions/julia-buildpkg@v1
      env:
        PYTHON: /home/runner/.capy-venv/bin/python

    - name: Run test suite
      uses: julia-actions/julia-runtest@v1
      env:
        PYTHON: /home/runner/.capy-venv/bin/python
